import { getMapJSON } from "dotted-map";
import fs from "fs";
import path from "path";

/**
 * ISO 3166-1 alpha-3 codes for continental Africa + nearby islands.
 * `dotted-map` ships a reduced Natural Earth–style dataset: several small
 * island states have no polygon, so including them makes `getMapJSON` crash
 * (undefined features in the FeatureCollection).
 */
const AFRICA_COUNTRIES_RAW = [
  "DZA",
  "AGO",
  "BEN",
  "BWA",
  "BFA",
  "BDI",
  "CMR",
  "CPV", // not in dotted-map bundle
  "CAF",
  "TCD",
  "COM", // not in dotted-map bundle
  "COD",
  "COG",
  "CIV",
  "DJI",
  "EGY",
  "GNQ",
  "ERI",
  "SWZ",
  "ETH",
  "GAB",
  "GMB",
  "GHA",
  "GIN",
  "GNB",
  "KEN",
  "LSO",
  "LBR",
  "LBY",
  "MDG",
  "MWI",
  "MLI",
  "MRT",
  "MUS", // not in dotted-map bundle
  "MAR",
  "MOZ",
  "NAM",
  "NER",
  "NGA",
  "RWA",
  "STP", // not in dotted-map bundle
  "SEN",
  "SYC", // not in dotted-map bundle
  "SLE",
  "SOM",
  "ZAF",
  "SSD",
  "SDN",
  "TZA",
  "TGO",
  "TUN",
  "UGA",
  "ESH",
  "ZMB",
  "ZWE",
] as const;

/** Confirmed absent from `dotted-map@3.1.0` country features (see node_modules build). */
const DOTTED_MAP_MISSING_AFRICA: ReadonlySet<string> = new Set([
  "CPV",
  "COM",
  "MUS",
  "STP",
  "SYC",
]);

const AFRICA_COUNTRIES = AFRICA_COUNTRIES_RAW.filter(
  (code) => !DOTTED_MAP_MISSING_AFRICA.has(code),
);

const excluded = AFRICA_COUNTRIES_RAW.filter((code) =>
  DOTTED_MAP_MISSING_AFRICA.has(code),
);
if (excluded.length > 0) {
  console.warn(
    "Skipping countries not present in dotted-map GeoJSON:",
    excluded.join(", "),
  );
}

const mapJsonString = getMapJSON({
  height: 120,
  grid: "diagonal",
  countries: [...AFRICA_COUNTRIES],
});

/** Run from monorepo root: `pnpm exec tsx scripts/generate-africa-map.ts` */
const outputPath = path.join(
  process.cwd(),
  "apps",
  "web",
  "src",
  "components",
  "africa-map-data.ts",
);

fs.mkdirSync(path.dirname(outputPath), { recursive: true });

fs.writeFileSync(
  outputPath,
  `// Generated by scripts/generate-africa-map.ts — do not edit by hand.\n` +
    `const africaMapJson = ${JSON.stringify(mapJsonString)};\n\nexport default africaMapJson;\n`,
);

console.log("Africa map JSON written to:", outputPath);
